spring:
  datasource:
    url: jdbc:mysql://ukma:1234@68.183.216.120:3306/schedule
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        hbm2ddl:
          auto: update
